<a href="https://colab.research.google.com/github/PravinV001/Python/blob/Class_N_Colab/Demo_April_27_sklearn_Pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Loan Approval
import pandas as pd
df = pd.read_csv('/content/loans.csv')

df.head()

,id,member_id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,...,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,last_pymnt_amnt,loan_status
0,1077501,1296599.0,5000.0,36 months,10.65%,162.87,B,B2,10+ years,RENT,...,27.65,0.0,1.0,3.0,0.0,13648.0,83.7%,9.0,171.62,Fully Paid
1,1077430,1314167.0,2500.0,60 months,15.27%,59.83,C,C4,< 1 year,RENT,...,1.00,0.0,5.0,3.0,0.0,1687.0,9.4%,4.0,119.66,Charged Off
2,1077175,1313524.0,2400.0,36 months,15.96%,84.33,C,C5,10+ years,RENT,...,8.72,0.0,2.0,2.0,0.0,2956.0,98.5%,10.0,649.91,Fully Paid
3,1076863,1277178.0,10000.0,36 months,13.49%,339.31,C,C1,10+ years,RENT,...,20.00,0.0,1.0,10.0,0.0,5598.0,21%,37.0,357.48,Fully Paid
4,1075269,1311441.0,5000.0,36 months,7.90%,156.46,A,A4,3 years,RENT,...,11.20,0.0,3.0,9.0,0.0,7963.0,28.3%,12.0,161.03,Fully Paid

In [ ]:
pd.set_option('display.max_columns', None)

In [ ]:
df.head()

,id,member_id,loan_amnt,term,int_rate,installment,grade,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,last_pymnt_amnt,loan_status
0,1077501,1296599.0,5000.0,36 months,10.65%,162.87,B,B2,10+ years,RENT,24000.0,Verified,credit_card,27.65,0.0,1.0,3.0,0.0,13648.0,83.7%,9.0,171.62,Fully Paid
1,1077430,1314167.0,2500.0,60 months,15.27%,59.83,C,C4,< 1 year,RENT,30000.0,Source Verified,car,1.00,0.0,5.0,3.0,0.0,1687.0,9.4%,4.0,119.66,Charged Off
2,1077175,1313524.0,2400.0,36 months,15.96%,84.33,C,C5,10+ years,RENT,12252.0,Not Verified,small_business,8.72,0.0,2.0,2.0,0.0,2956.0,98.5%,10.0,649.91,Fully Paid
3,1076863,1277178.0,10000.0,36 months,13.49%,339.31,C,C1,10+ years,RENT,49200.0,Source Verified,other,20.00,0.0,1.0,10.0,0.0,5598.0,21%,37.0,357.48,Fully Paid
4,1075269,1311441.0,5000.0,36 months,7.90%,156.46,A,A4,3 years,RENT,36000.0,Source Verified,wedding,11.20,0.0,3.0,9.0,0.0,7963.0,28.3%,12.0,161.03,Fully Paid

In [ ]:
cols_to_drop = ['id'	, 'member_id', 'last_pymnt_amnt', 'grade', 'installment']
df.drop(columns=cols_to_drop, inplace=True)

In [ ]:
df.head()

,loan_amnt,term,int_rate,sub_grade,emp_length,home_ownership,annual_inc,verification_status,purpose,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,loan_status
0,5000.0,36 months,10.65%,B2,10+ years,RENT,24000.0,Verified,credit_card,27.65,0.0,1.0,3.0,0.0,13648.0,83.7%,9.0,Fully Paid
1,2500.0,60 months,15.27%,C4,< 1 year,RENT,30000.0,Source Verified,car,1.00,0.0,5.0,3.0,0.0,1687.0,9.4%,4.0,Charged Off
2,2400.0,36 months,15.96%,C5,10+ years,RENT,12252.0,Not Verified,small_business,8.72,0.0,2.0,2.0,0.0,2956.0,98.5%,10.0,Fully Paid
3,10000.0,36 months,13.49%,C1,10+ years,RENT,49200.0,Source Verified,other,20.00,0.0,1.0,10.0,0.0,5598.0,21%,37.0,Fully Paid
4,5000.0,36 months,7.90%,A4,3 years,RENT,36000.0,Source Verified,wedding,11.20,0.0,3.0,9.0,0.0,7963.0,28.3%,12.0,Fully Paid

In [ ]:
df['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [ ]:
df['term'] = df['term'].str.replace(' months', '').str.strip().astype(int)

In [ ]:
df['int_rate'] = df['int_rate'].str.replace('%', '').astype(float)

In [ ]:
df['revol_util'] = df['revol_util'].str.replace('%', '').astype(float)

In [ ]:
df['sub_grade'].unique()

array(['B2', 'C4', 'C5', 'C1', 'A4', 'E1', 'F2', 'B5', 'C3', 'B1', 'D1',
       'A1', 'B3', 'B4', 'C2', 'D2', 'A3', 'A5', 'D5', 'A2', 'E4', 'D3',
       'D4', 'F3', 'E3', 'F1', 'E5', 'G4', 'E2', 'G2', 'G1', 'F5', 'F4',
       'G5', 'G3'], dtype=object)

In [ ]:
risk_mapping = {
    'A1': 0,  'A2': 1,  'A3': 2,  'A4': 3,  'A5': 4,
    'B1': 5,  'B2': 6,  'B3': 7,  'B4': 8,  'B5': 9,
    'C1': 10, 'C2': 11, 'C3': 12, 'C4': 13, 'C5': 14,
    'D1': 15, 'D2': 16, 'D3': 17, 'D4': 18, 'D5': 19,
    'E1': 20, 'E2': 21, 'E3': 22, 'E4': 23, 'E5': 24,
    'F1': 25, 'F2': 26, 'F3': 27, 'F4': 28, 'F5': 29,
    'G1': 30, 'G2': 31, 'G3': 32, 'G4': 33, 'G5': 34
}


df['sub_grade'] = df['sub_grade'].map(risk_mapping) # Ordinal Encoding!

In [ ]:
df['loan_status'].unique()

array(['Fully Paid', 'Charged Off'], dtype=object)

In [ ]:
df['loan_status'] = df['loan_status'].map({'Fully Paid':0, 'Charged Off':1})

In [ ]:
from sklearn.base import BaseEstimator, TransformerMixin
import pandas as pd
import numpy as np

# Capping --> Winsorization
# --------------------------------------------------
# Custom Outlier Capping Transformer using IQR
# --------------------------------------------------
class OutlierCapper(BaseEstimator, TransformerMixin):
    def __init__(self, factor=1.5):
        self.factor = factor

    def fit(self, X, y=None):
        X = pd.DataFrame(X)

        self.lower_bounds_ = {}
        self.upper_bounds_ = {}

        for col in X.columns:
            Q1 = X[col].quantile(0.25)
            Q3 = X[col].quantile(0.75)
            IQR = Q3 - Q1

            lower = Q1 - self.factor * IQR
            upper = Q3 + self.factor * IQR

            self.lower_bounds_[col] = lower
            self.upper_bounds_[col] = upper

        return self

    def transform(self, X):
        X = pd.DataFrame(X).copy()

        for col in X.columns:
            lower = self.lower_bounds_[col]
            upper = self.upper_bounds_[col]

            X[col] = np.where(X[col] < lower, lower, X[col])
            X[col] = np.where(X[col] > upper, upper, X[col])

        return X

In [ ]:
df.columns

Index(['loan_amnt', 'term', 'int_rate', 'sub_grade', 'emp_length',
       'home_ownership', 'annual_inc', 'verification_status', 'purpose', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'loan_status'],
      dtype='object')

In [ ]:
# Correlation Finder and Remover of Redundant Features!
class CorrelationFilterWithScoring(BaseEstimator, TransformerMixin):
    def __init__(self, threshold=0.9):
        self.threshold = threshold

    def fit(self, X, y=None):
        X = pd.DataFrame(X).copy()
        y = pd.Series(y)

        corr_matrix = X.corr().abs()  #corr b/w the features!

        # Correlation of each feature with target
        target_corr = X.apply(lambda col: abs(col.corr(y)))  #corr of each feature with the output

        columns_to_drop = set()

        for i in range(len(corr_matrix.columns)):
            for j in range(i):
                col1 = corr_matrix.columns[i]
                col2 = corr_matrix.columns[j]

                if corr_matrix.iloc[i, j] > self.threshold:
                    score1 = target_corr[col1]
                    score2 = target_corr[col2]

                    # Drop the weaker feature
                    if score1 < score2:
                        columns_to_drop.add(col1)
                    else:
                        columns_to_drop.add(col2)

        self.columns_to_drop_ = list(columns_to_drop)

        return self

    def transform(self, X):
        X = pd.DataFrame(X).copy()
        return X.drop(columns=self.columns_to_drop_, errors='ignore')

In [ ]:
df.columns

Index(['loan_amnt', 'term', 'int_rate', 'sub_grade', 'emp_length',
       'home_ownership', 'annual_inc', 'verification_status', 'purpose', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'loan_status'],
      dtype='object')

In [ ]:
df['emp_length'].unique()

array(['10+ years', '< 1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '1 year', '6 years', '2 years', '7 years',
       nan], dtype=object)

In [ ]:
emp_length_mapping = {
    '< 1 year': 0,
    '1 year': 1,
    '2 years': 2,
    '3 years': 3,
    '4 years': 4,
    '5 years': 5,
    '6 years': 6,
    '7 years': 7,
    '8 years': 8,
    '9 years': 9,
    '10+ years': 10,
    np.nan: np.nan
}

df['emp_length'] = df['emp_length'].map(emp_length_mapping)

In [ ]:
df.columns

Index(['loan_amnt', 'term', 'int_rate', 'sub_grade', 'emp_length',
       'home_ownership', 'annual_inc', 'verification_status', 'purpose', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'loan_status'],
      dtype='object')

In [ ]:
df.columns

Index(['loan_amnt', 'term', 'int_rate', 'sub_grade', 'emp_length',
       'home_ownership', 'annual_inc', 'verification_status', 'purpose', 'dti',
       'delinq_2yrs', 'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'loan_status'],
      dtype='object')

In [ ]:
num_cols = ['loan_amnt', 'term', 'int_rate', 'annual_inc', 'dti', 'delinq_2yrs',
            'inq_last_6mths', 'open_acc', 'pub_rec', 'revol_bal', 'revol_util', 'total_acc', 'sub_grade', 'emp_length']

df[num_cols].dtypes

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

steps_num_features = [('si', SimpleImputer()), ('oc', OutlierCapper()), ('ss', StandardScaler()),
 ('fs', CorrelationFilterWithScoring())]

num_pipeline = Pipeline(steps = steps_num_features)


nom_features = ['home_ownership', 'verification_status', 'purpose']
from sklearn.preprocessing import OneHotEncoder
steps_nom_features = [('si2', SimpleImputer(strategy = 'most_frequent')), ('OHE', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)), ('ss', StandardScaler()),
 ('fs', CorrelationFilterWithScoring())]
nom_pipeline = Pipeline(steps = steps_nom_features)


from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer([('num_pipe', num_pipeline, num_cols), ('nom_pipe', nom_pipeline, nom_features)], remainder = 'drop')

from sklearn.neighbors import KNeighborsClassifier
final_pipeline = Pipeline([('preprocess', preprocessor), ('model', KNeighborsClassifier())])

X = df.drop('loan_status', axis = 1) # Fetaures
y = df['loan_status'] # Target


from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 1)


final_pipeline.fit(X_train, y_train)



# Feature Selection
# |Corr(X_i, X_j)| > 0.9
# |Corr(X_i, Y)| --> a1
# |Corr(X_j, Y)| --> b1
# if a1 >  b1 --> Drop X_j

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num_pipe',
                                                  Pipeline(steps=[('si',
                                                                   SimpleImputer()),
                                                                  ('oc',
                                                                   OutlierCapper()),
                                                                  ('ss',
                                                                   StandardScaler()),
                                                                  ('fs',
                                                                   CorrelationFilterWithScoring())]),
                                                  ['loan_amnt', 'term',
                                                   'int_rate', 'annual_inc',
                                                   'dti', 'delinq_2yrs',
                                                   'inq_last_6mths', 'open_acc',
                                                   'pub_rec', 'revol_bal',
                                                   'revol_util', 'total_acc',
                                                   'sub_grade', 'emp_length']),
                                                 ('nom_pipe',
                                                  Pipeline(steps=[('si2',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('OHE',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False)),
                                                                  ('ss',
                                                                   StandardScaler()),
                                                                  ('fs',
                                                                   CorrelationFilterWithScoring())]),
                                                  ['home_ownership',
                                                   'verification_status',
                                                   'purpose'])])),
                ('model', KNeighborsClassifier())])

In [ ]:
preds = final_pipeline.predict(X_test)
preds

array([0, 0, 0, ..., 0, 0, 1])

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.85      0.97      0.91      9890
           1       0.23      0.05      0.08      1741

    accuracy                           0.83     11631
   macro avg       0.54      0.51      0.50     11631
weighted avg       0.76      0.83      0.78     11631

In [ ]:
from sklearn.model_selection import RandomizedSearchCV
hyper_params = {'model__n_neighbors':[1, 2, 3, 4],
                'model__metric':['euclidean', 'manhattan'],
                'model__weights': ['uniform', 'distance'],
                'preprocess__num_pipe__si__strategy': ['mean', 'median']}

from sklearn.model_selection import StratifiedKFold
skf = StratifiedKFold(n_splits = 5, shuffle = True, random_state = 1)

# final_pipeline = Pipeline([('preprocessor', preprocessor), ('model', KNeighborsClassifier())])
rcv = RandomizedSearchCV(final_pipeline, hyper_params, cv = skf, scoring = 'f1', n_iter = 10)
rcv.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=1, shuffle=True),
                   estimator=Pipeline(steps=[('preprocess',
                                              ColumnTransformer(transformers=[('num_pipe',
                                                                               Pipeline(steps=[('si',
                                                                                                SimpleImputer()),
                                                                                               ('oc',
                                                                                                OutlierCapper()),
                                                                                               ('ss',
                                                                                                StandardScaler()),
                                                                                               ('fs',
                                                                                                CorrelationFilterWithScoring())]),
                                                                               ['loan_amnt',
                                                                                'term',
                                                                                'int_rate',
                                                                                'annual_inc',
                                                                                'dti',
                                                                                'delinq_2yrs...
                                                                                                StandardScaler()),
                                                                                               ('fs',
                                                                                                CorrelationFilterWithScoring())]),
                                                                               ['home_ownership',
                                                                                'verification_status',
                                                                                'purpose'])])),
                                             ('model',
                                              KNeighborsClassifier())]),
                   param_distributions={'model__metric': ['euclidean',
                                                          'manhattan'],
                                        'model__n_neighbors': [1, 2, 3, 4],
                                        'model__weights': ['uniform',
                                                           'distance'],
                                        'preprocess__num_pipe__si__strategy': ['mean',
                                                                               'median']},
                   scoring='f1')

In [ ]:
rcv.best_params_

{'preprocess__num_pipe__si__strategy': 'median',
 'model__weights': 'distance',
 'model__n_neighbors': 1,
 'model__metric': 'euclidean'}

In [ ]:
rcv.best_estimator_

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num_pipe',
                                                  Pipeline(steps=[('si',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('oc',
                                                                   OutlierCapper()),
                                                                  ('ss',
                                                                   StandardScaler()),
                                                                  ('fs',
                                                                   CorrelationFilterWithScoring())]),
                                                  ['loan_amnt', 'term',
                                                   'int_rate', 'annual_inc',
                                                   'dti', 'delinq_2yrs',
                                                   'inq_last_6mths', 'open_acc',
                                                   'pub_rec', 'revol_bal',
                                                   'revol_util', 'total...
                                                   'sub_grade', 'emp_length']),
                                                 ('nom_pipe',
                                                  Pipeline(steps=[('si2',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('OHE',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False)),
                                                                  ('ss',
                                                                   StandardScaler()),
                                                                  ('fs',
                                                                   CorrelationFilterWithScoring())]),
                                                  ['home_ownership',
                                                   'verification_status',
                                                   'purpose'])])),
                ('model',
                 KNeighborsClassifier(metric='euclidean', n_neighbors=1,
                                      weights='distance'))])

In [ ]:
preds = rcv.best_estimator_.predict(X_test)
preds

array([1, 1, 0, ..., 0, 1, 1])

In [ ]:
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.86      0.86      0.86      9890
           1       0.19      0.18      0.18      1741

    accuracy                           0.76     11631
   macro avg       0.52      0.52      0.52     11631
weighted avg       0.76      0.76      0.76     11631

In [ ]:
y_true = np.array([1, 0, 0, 1])
y_pred = np.array([1, 1, 0, 0])

((y_true == 1) & (y_pred == 0)).sum()  # fn

np.int64(1)

In [ ]:
def custom_bus_metric(y_true, y_pred):
  fn = ((y_true == 1) & (y_pred == 0)).sum()
  fp = ((y_true == 0) & (y_pred == 1)).sum()
  return (100*fn + 10*fp)

from sklearn.metrics import make_scorer
custom_scorer = make_scorer(custom_bus_metric, greater_is_better = False)

rcv = RandomizedSearchCV(final_pipeline, hyper_params, cv = skf, scoring = custom_scorer, n_iter = 3)
rcv.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

RandomizedSearchCV(cv=StratifiedKFold(n_splits=5, random_state=1, shuffle=True),
                   estimator=Pipeline(steps=[('preprocess',
                                              ColumnTransformer(transformers=[('num_pipe',
                                                                               Pipeline(steps=[('si',
                                                                                                SimpleImputer()),
                                                                                               ('oc',
                                                                                                OutlierCapper()),
                                                                                               ('ss',
                                                                                                StandardScaler()),
                                                                                               ('fs',
                                                                                                CorrelationFilterWithScoring())]),
                                                                               ['loan_amnt',
                                                                                'term',
                                                                                'int_rate',
                                                                                'annual_inc',
                                                                                'dti',
                                                                                'delinq_2yrs...
                                                                                'verification_status',
                                                                                'purpose'])])),
                                             ('model',
                                              KNeighborsClassifier())]),
                   n_iter=3,
                   param_distributions={'model__metric': ['euclidean',
                                                          'manhattan'],
                                        'model__n_neighbors': [1, 2, 3, 4],
                                        'model__weights': ['uniform',
                                                           'distance'],
                                        'preprocess__num_pipe__si__strategy': ['mean',
                                                                               'median']},
                   scoring=make_scorer(custom_bus_metric, greater_is_better=False, response_method='predict'))

In [ ]:
rcv.best_params_

{'preprocess__num_pipe__si__strategy': 'mean',
 'model__weights': 'distance',
 'model__n_neighbors': 2,
 'model__metric': 'manhattan'}

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Based on the custom business metric
preds = rcv.best_estimator_.predict(X_test)
print(classification_report(y_test, preds))

              precision    recall  f1-score   support

           0       0.86      0.87      0.86      9890
           1       0.20      0.19      0.19      1741

    accuracy                           0.76     11631
   macro avg       0.53      0.53      0.53     11631
weighted avg       0.76      0.76      0.76     11631

In [ ]:
# Deal with Outliers
# Remove the outlier samples
# Cap the outliers [Winsorization]
# val > threshold --> set it to the threshold
# val (160) > Q3 + 1.5 *  IQR [140] --> set it to 140 -->      #IQR =  Q3 - Q1
# val  < Q1 - 1.5 *  IQR --> set the val to  Q1 - 1.5 *  IQR

# val > 0.99th percentile
# val > some_num (threshold)   -->  replace the val with the threshold [Capping an Outlier]

In [ ]:
from sklearn.preprocessing import FunctionTransformer, StandardScaler
from sklearn.compose import ColumnTransformer

df = pd.DataFrame({
    "rate": ["45%", "60%", "75%"],
    "value": [10, 20, 30]
})

# Step 1: remove %
def clean_rate(x):
    return x.str.replace('%', '').astype(float)

rate_pipeline = Pipeline([
    ("remove_percent", FunctionTransformer(lambda x: clean_rate(x.squeeze()).to_frame())),
    ("scale", StandardScaler())
])

preprocessor = ColumnTransformer([
    ("rate_proc", rate_pipeline, ["rate"])
], remainder='passthrough')

result = preprocessor.fit_transform(df)
print(result)

In [ ]:
!pip install lazypredict

Collecting lazypredict
  Downloading lazypredict-0.3.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from lazypredict) (8.3.2)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (1.6.1)
Requirement already satisfied: pandas>=1.3 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (2.2.2)
Requirement already satisfied: tqdm>=4.0 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (4.67.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (1.5.3)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.12/dist-packages (from lazypredict) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->lazypredict) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->lazypredict) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3->lazypredict) (2026.1)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->lazypredict) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->lazypredict) (3.6.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3->lazypredict) (1.17.0)
Downloading lazypredict-0.3.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 2.5 MB/s eta 0:00:00
Installing collected packages: lazypredict
Successfully installed lazypredict-0.3.0

In [ ]:
from lazypredict.Supervised import LazyClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split

data = load_breast_cancer()
X = data.data
y = data.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=123)

clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

print(models)

                               Accuracy  Balanced Accuracy   ROC AUC  \
Model
LinearSVC                      0.989474           0.987544  0.992478
Perceptron                     0.985965           0.984797  0.993225
LogisticRegression             0.985965           0.982690  0.994719
XGBClassifier                  0.982456           0.982050  0.990238
SVC                            0.982456           0.979942  0.994879
LabelSpreading                 0.975439           0.974448       NaN
LabelPropagation               0.975439           0.974448       NaN
BaggingClassifier              0.971930           0.973808  0.986024
PassiveAggressiveClassifier    0.978947           0.972981  0.996213
SGDClassifier                  0.975439           0.972341  0.991785
RandomForestClassifier         0.971930           0.971701  0.993252
CalibratedClassifierCV         0.978947           0.970874  0.993865
AdaBoostClassifier             0.971930           0.969594  0.990558
LGBMClassifier                 0.968421           0.966846  0.989544
QuadraticDiscriminantAnalysis  0.964912           0.966206  0.987357
ExtraTreesClassifier           0.968421           0.964739  0.994932
RidgeClassifierCV              0.971930           0.963272  0.992372
RidgeClassifier                0.968421           0.960525  0.991945
KNeighborsClassifier           0.961404           0.955030  0.986584
BernoulliNB                    0.950877           0.951003  0.989918
LinearDiscriminantAnalysis     0.961404           0.950816  0.982290
GaussianNB                     0.954386           0.949536  0.993492
NuSVC                          0.954386           0.943215  0.991785
ExtraTreeClassifier            0.943860           0.934973  0.934973
NearestCentroid                0.947368           0.933506  0.989144
DecisionTreeClassifier         0.929825           0.928198  0.928198
DummyClassifier                0.638596           0.500000  0.500000

                               F1 Score  Precision    Recall  Time Taken
Model
LinearSVC                      0.989462   0.989478  0.989474    0.067284
Perceptron                     0.985965   0.985965  0.985965    0.021773
LogisticRegression             0.985934   0.986010  0.985965    0.047029
XGBClassifier                  0.982474   0.982519  0.982456    0.232161
SVC                            0.982437   0.982445  0.982456    0.040744
LabelSpreading                 0.975464   0.975515  0.975439    0.050467
LabelPropagation               0.975464   0.975515  0.975439    0.059944
BaggingClassifier              0.972041   0.972559  0.971930    0.151503
PassiveAggressiveClassifier    0.978853   0.979183  0.978947    0.039545
SGDClassifier                  0.975412   0.975412  0.975439    0.031446
RandomForestClassifier         0.971987   0.972147  0.971930    0.225987
CalibratedClassifierCV         0.978802   0.979619  0.978947    0.178297
AdaBoostClassifier             0.971930   0.971930  0.971930    0.359308
LGBMClassifier                 0.968454   0.968512  0.968421    0.165448
QuadraticDiscriminantAnalysis  0.965052   0.965594  0.964912    0.061625
ExtraTreesClassifier           0.968387   0.968379  0.968421    0.270823
RidgeClassifierCV              0.971736   0.972497  0.971930    0.030363
RidgeClassifier                0.968242   0.968720  0.968421    0.025150
KNeighborsClassifier           0.961276   0.961381  0.961404    0.041436
BernoulliNB                    0.951072   0.951663  0.950877    0.055298
LinearDiscriminantAnalysis     0.961089   0.962061  0.961404    0.119461
GaussianNB                     0.954337   0.954314  0.954386    0.051862
NuSVC                          0.954014   0.954918  0.954386    0.088763
ExtraTreeClassifier            0.943609   0.943764  0.943860    0.038535
NearestCentroid                0.946801   0.948345  0.947368    0.038299
DecisionTreeClassifier         0.930103   0.930768  0.929825    0.079633
DummyClassifier                0.497750   0.407805  0.638596    0.035970

In [ ]:
models

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
LinearSVC,0.989474,0.987544,0.992478,0.989462,0.989478,0.989474,0.067284
Perceptron,0.985965,0.984797,0.993225,0.985965,0.985965,0.985965,0.021773
LogisticRegression,0.985965,0.982690,0.994719,0.985934,0.986010,0.985965,0.047029
XGBClassifier,0.982456,0.982050,0.990238,0.982474,0.982519,0.982456,0.232161
SVC,0.982456,0.979942,0.994879,0.982437,0.982445,0.982456,0.040744
LabelSpreading,0.975439,0.974448,NaN,0.975464,0.975515,0.975439,0.050467
LabelPropagation,0.975439,0.974448,NaN,0.975464,0.975515,0.975439,0.059944
BaggingClassifier,0.971930,0.973808,0.986024,0.972041,0.972559,0.971930,0.151503
PassiveAggressiveClassifier,0.978947,0.972981,0.996213,0.978853,0.979183,0.978947,0.039545
SGDClassifier,0.975439,0.972341,0.991785,0.975412,0.975412,0.975439,0.031446
RandomForestClassifier,0.971930,0.971701,0.993252,0.971987,0.972147,0.971930,0.225987
CalibratedClassifierCV,0.978947,0.970874,0.993865,0.978802,0.979619,0.978947,0.178297
AdaBoostClassifier,0.971930,0.969594,0.990558,0.971930,0.971930,0.971930,0.359308
LGBMClassifier,0.968421,0.966846,0.989544,0.968454,0.968512,0.968421,0.165448
QuadraticDiscriminantAnalysis,0.964912,0.966206,0.987357,0.965052,0.965594,0.964912,0.061625
ExtraTreesClassifier,0.968421,0.964739,0.994932,0.968387,0.968379,0.968421,0.270823
RidgeClassifierCV,0.971930,0.963272,0.992372,0.971736,0.972497,0.971930,0.030363
RidgeClassifier,0.968421,0.960525,0.991945,0.968242,0.968720,0.968421,0.025150
KNeighborsClassifier,0.961404,0.955030,0.986584,0.961276,0.961381,0.961404,0.041436
BernoulliNB,0.950877,0.951003,0.989918,0.951072,0.951663,0.950877,0.055298
LinearDiscriminantAnalysis,0.961404,0.950816,0.982290,0.961089,0.962061,0.961404,0.119461
GaussianNB,0.954386,0.949536,0.993492,0.954337,0.954314,0.954386,0.051862
NuSVC,0.954386,0.943215,0.991785,0.954014,0.954918,0.954386,0.088763
ExtraTreeClassifier,0.943860,0.934973,0.934973,0.943609,0.943764,0.943860,0.038535
NearestCentroid,0.947368,0.933506,0.989144,0.946801,0.948345,0.947368,0.038299
DecisionTreeClassifier,0.929825,0.928198,0.928198,0.930103,0.930768,0.929825,0.079633
DummyClassifier,0.638596,0.500000,0.500000,0.497750,0.407805,0.638596,0.035970

In [ ]:
# H20.ai, Databricks, PyCaret, MLJAR, ..


# Suggestions to improve:
Feature Engineering Beyond Cleaning
Kindly note that Tree models don’t always discover optimal cross-boundary interactions. Consider extracting more features.
Try combinations like:
- Instead of raw dti: Create bins: 0–10, 10–20, 20–30, 30+ --> Tree models benefit from this discretization. Same can be done for income.
- Revol Util × DTI
- revol_util × revol_bal
- Instead of one-hot, do target encoding for all high cardinality features.
- Consider binning loan_amount and other continuous features to provide more signal to your model.
- Loan data often has: Extreme income -->. Use: Winsorization and Log transforms
- log(annual_inc) as Income distribution is skewed.
- log(loan_amt) might improve linear models.
- loan_amnt / annual_inc
- inq_last_6mths > 2 --> Captures aggressive borrowing.- installment / monthly_income
- term_60_month AND grade >= D  --> Long term + risky grade = dangerous.
- Create a composite risk score: Standardize and combine: DTI, Installment ratio, Revol util, Delinq count, Inquiry count. Then sum.
- Delinquency Intensity Score --> 2×delinq_2yrs+pub_rec    --> Weighted past delinquency behavior.
- Inquiries per Credit Line: inq_last_6mths/total_acc --> Measures credit hunger.
- Income Stability Proxy: annual_inc/ (emp_length + 1) --> Short employment + high income may signal instability.
For Lending Club, feature engineering > model choice.

Try Gradient Boosting variants
Compare LightGBM, XGBoost, and CatBoost using ROC-AUC and PR-AUC
Not just on accuracy/custom-cost-metric.
CatBoost also handles categorical features better. Often outperforms on Lending Club

Discuss why the numbers are bad.
The dataset contains only approved loans [Reject Inference Bias].
Therefore: Model is trained on pre-screened applicants. Selection bias exists.

Consider exploring the prob. calibration plot.

Try SMOTE variants. Tune sampling_strategy via CV.
In similar problems, be very careful as SMOTE can distort probability calibration.

Sometimes,  instead of one model: Train separate models per grade band helps. Or high-income vs low-income groups. This can increase precision by 5–10%.
- Split dataset into: Grade A–C, Grade D–G

Try Focal Loss instead of log-loss: Helps when precision is low.

Heterogeneous Ensemble: Stack logistic + tree + boosting or Meta learner on probabilities
Often gives 2–5% improvement.